spring:
  datasource:
    url: jdbc:mysql://db:3306/ec?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 # 連接池初始化大小
      min-idle: 10 # 最小空閒連接數
      max-active: 20 # 最大連接數
      web-stat-filter:
        exclusions: "*.js, *.gif, *.jpg, *.png, *.css, *.ico, /druid/*" # 不統計這些請求數據
      stat-view-servlet: # 訪問監控網頁的登錄用戶名和密碼
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: es:9200

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.rsosor.ec: info

logstash:
  host: logstash